name: PR Conventional Commits

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Conventional Commits Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check every commit
        uses: webiny/action-conventional-commits@v1.0.3
