name: PR Tag Version

on:
  pull_request:
    types:
      - closed

env:
  GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
  LABEL_PREFIX: version/

jobs:
  build-version:
    name: Build Version
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get release based on Label
        uses: actions-ecosystem/action-release-label@v1
        id: release-label
        with:
          label_prefix: ${{ env.LABEL_PREFIX }}

      - name: Get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true

      - name: Increase semver based on release value
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}

      - name: Create tag
        uses: julb/action-manage-tag@v1
        with:
          name: ${{ steps.bump-semver.outputs.new_version }}
        env:
          token: ${{ env.GITHUB_TOKEN }}

      - name: Push new version tag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
